### ISSUE TITLE
API Usuario

### ISSUE THREAD

**Issue by St3v3n-4n4** [St3v3n-4n4/APIG4C4#2]

**Comment by jwalzategit** [comment]
API Usuario funcionando. Se creó el API en Loopback y además ya tiene la integración con el API de Notificaciones.

**Comment by jwalzategit** [comment]
#### Código del requisito | RF-001

### Nombre: Crear usuario
### Propósito: Permitir al actor, crear un nuevo usuario para el uso de la   aplicación
### Descripción: Una vez el usuario (ya registrado), inicia su sesión, podrá dirigirse   al menú de gestión de usuarios, dar clic en crear usuario y debe diligenciar   todos los campos solicitados allí. Cuando termine, dará clic en guardar para   que los cambios queden efectuados (se debe realizar un proceso de validación)
### Entrada: Ingresar los datos completos del usuario a crear. (los que se pidan   en el formulario)
### Salida: Mostrar mensaje en pantalla donde se indique el resultado final de la   transacción

**Comment by jwalzategit** [comment]
### Código del requisito | RF-004

**Nombre**: Eliminar Usuario
**Propósito**: Permitir al actor eliminar un usuario
**Descripción**: El actor accede a la opción de eliminación de usuarios, busca el usuario que desea eliminar, y da clic en la opción eliminar
**Entrada**: Ingresar el Id del usuario
**Salida**: Mostrar mensaje en pantalla advirtiendo que el registro será eliminado, si el actor acepta, la eliminación se ejecutará, en caso contrario la acción no se realiza
