### ISSUE TITLE
API Rutas

### ISSUE THREAD

**Issue by St3v3n-4n4** [St3v3n-4n4/APIG4C4#4]

**Comment by jwalzategit** [comment]
# Descripción

Registrar, consultar, editar y eliminar Rutas, las cuales tienen la siguiente información: (id, origen, destino, tiempo estimado), el origen y destino son Aeropuertos previamente registrados y deben ser diferentes.

**Comment by jwalzategit** [comment]
# Código del requisito `RF-011`

## Nombre `Crear Vuelo`

## Propósito
Permitir al usuario, crear las diferentes rutas en las cuales podrán operar los diferentes vuelos

## Descripción
Una vez el usuario, inicia su sesión, podrá dirigirse al menú de gestión de rutas, dar clic en crear rutas y debe diligenciar todos los campos solicitados allí. Cuando termine, dará clic en guardar para que los cambios queden efectuados. (se realiza un proceso de validación)

## Entrada
Ingresar los datos completos de la ruta a crear (diligenciar formulario)

## Salida
Mostrar mensaje en pantalla donde se indique cuál fue el resultado final de la acción crear Ruta

## Prioridad
`Alta`

**Comment by jwalzategit** [comment]
# Código del requisito `RF-012`

## Nombre `Modificar Ruta`

## Propósito
Permitir al actor del sistema, modificar los datos generales de una Ruta.

## Descripción
Una vez el actor, inicia su sesión, podrá dirigirse al menú de gestión de Rutas, dar clic en modificar Ruta y debe diligenciar todos los campos solicitados allí. Cuando termine, dará clic en modificar para que los cambios queden efectuados.  (se realiza un proceso de validación)

## Entrada
Ingresar los datos completos de la Ruta a modificar

## Salida
Mostrar mensaje en pantalla donde se indique que la acción fue cumplida satisfactoriamente

## Prioridad
`Alta`

**Comment by jwalzategit** [comment]
# Código del requisito `RF-013`

## Nombre `Buscar Ruta`

## Propósito
Permitir al actor del sistema, buscar una Ruta y mostrar los datos generales de la Ruta

## Descripción
Una vez el actor, inicia su sesión, podrá dirigirse al menú de gestión de Rutas, dar clic en buscar Ruta y debe diligenciar el Id de la Ruta a buscar. Cuando termine, dará clic en buscar para que el sistema haga la búsqueda y traiga los demás datos de la Ruta si lo encuentra o un mensaje de “Ruta no encontrada” en caso contrario.

## Entrada
Ingresar el Id de la ruta a buscar

## Salida
Mostrar los datos de la Ruta encontrada o mensaje de “No encontrada"

## Prioridad
Alta

**Comment by jwalzategit** [comment]
# Código del requisito `RF-014`

## Nombre `Eliminar Ruta`

## Propósito
Permitir al actor eliminar una Ruta

## Descripción
El actor accede a la opción de eliminación de Ruta, busca la Ruta que desea eliminar, y da clic en la opción eliminar

## Entrada
Ingresar el identificador de la Ruta

## Salida
Mostrar mensaje en pantalla advirtiendo que el registro será eliminado, si el actor acepta, la eliminación se ejecutará, en caso contrario la acción no se realiza

## Prioridad
`Alta`
